# Generated by Django 5.2.7 on 2025-10-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('steam_app_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('genre', models.CharField(choices=[('fps', 'FPS'), ('rpg', 'RPG'), ('moba', 'MOBA'), ('survival', 'Survival'), ('strategy', 'Strategy'), ('puzzle', 'Puzzle'), ('adventure', 'Adventure'), ('simulation', 'Simulation'), ('other', 'Other')], default='other', max_length=50)),
                ('max_players', models.IntegerField(default=4)),
                ('min_players', models.IntegerField(default=2)),
                ('difficulty', models.CharField(choices=[('easy', '쉬움'), ('normal', '보통'), ('hard', '어려움'), ('extreme', '매우 어려움')], default='normal', max_length=20)),
                ('is_popular', models.BooleanField(default=False)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '게임',
                'verbose_name_plural': '게임들',
                'db_table': 'games',
                'ordering': ['-is_popular', 'name'],
            },
        ),
    ]
