# Generated by Django 5.2.7 on 2025-10-24 02:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('max_members', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)])),
                ('status', models.CharField(choices=[('open', '모집 중'), ('closed', '모집 마감'), ('in_progress', '진행 중'), ('completed', '완료')], default='open', max_length=20)),
                ('play_time', models.DateTimeField()),
                ('duration_hours', models.IntegerField(default=2)),
                ('required_skill', models.CharField(choices=[('any', '무관'), ('beginner', '초보'), ('intermediate', '중급'), ('advanced', '고급'), ('expert', '전문가')], default='any', max_length=20)),
                ('play_style', models.CharField(choices=[('any', '무관'), ('casual', '캐주얼'), ('serious', '진지함'), ('competitive', '경쟁적'), ('fun', '재미 위주')], default='any', max_length=20)),
                ('voice_chat_required', models.BooleanField(default=False)),
                ('discord_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '파티',
                'verbose_name_plural': '파티들',
                'db_table': 'parties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '파티 댓글',
                'verbose_name_plural': '파티 댓글들',
                'db_table': 'party_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_ready', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '파티 멤버',
                'verbose_name_plural': '파티 멤버들',
                'db_table': 'party_members',
            },
        ),
    ]
